### ISSUE TITLE
Spark submit crashes while running with Spark 1.6.x

### ISSUE THREAD

**Issue by mtomas** [saurfang/sbt-spark-submit#4]
Hello, 
thanks for the efforts on this plugin, I successfully used it without any problem while using Spark 1.4. However, it seems plugin is not yet compatible with Spark 1.6.

Here is the output of my custom task:

```
➜  spark-project-template sbt sampleApp
[info] Loading project definition from /Users/mtomas/development/private/spark-project-template/project
[info] Updating {file:/Users/mtomas/development/private/spark-project-template/project/}spark-project-template-build...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Compiling 2 Scala sources to /Users/mtomas/development/private/spark-project-template/project/target/scala-2.10/sbt-0.13/classes...
[info] Set current project to spark-project-template (in build file:/Users/mtomas/development/private/spark-project-template/)
[info] Updating {file:/Users/mtomas/development/private/spark-project-template/}spark-project-template...
Waiting for lock on /Users/mtomas/.ivy2/.sbt.ivy.lock to be available...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[warn] Scala version was updated by one of library dependencies:
[warn]  * org.scala-lang:scala-library:(2.10.4, 2.10.0) -> 2.10.5
[warn] To force scalaVersion, add the following:
[warn]  ivyScala := ivyScala.value map { _.copy(overrideScalaVersion = true) }
[warn] Run 'evicted' to see detailed eviction warnings
[info] Compiling 1 Scala source to /Users/mtomas/development/private/spark-project-template/target/scala-2.10/classes...
[info] Packaging /Users/mtomas/development/private/spark-project-template/target/scala-2.10/spark-project-template_2.10-0.1.jar ...
[info] Done packaging.
[info] Running org.apache.spark.deploy.SparkSubmit --class com.company.sample.App --master local[*] /Users/mtomas/development/private/spark-project-template/target/scala-2.10/spark-project-template_2.10-0.1.jar
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
16/05/16 02:29:02 INFO SparkContext: Running Spark version 1.6.1
16/05/16 02:29:02 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
16/05/16 02:29:03 INFO SecurityManager: Changing view acls to: mtomas
16/05/16 02:29:03 INFO SecurityManager: Changing modify acls to: mtomas
16/05/16 02:29:03 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: Set(mtomas); users with modify permissions: Set(mtomas)
16/05/16 02:29:03 INFO Utils: Successfully started service 'sparkDriver' on port 56499.
16/05/16 02:29:04 INFO Slf4jLogger: Slf4jLogger started
16/05/16 02:29:04 INFO Remoting: Starting remoting
16/05/16 02:29:04 INFO Remoting: Remoting started; listening on addresses :[akka.tcp://sparkDriverActorSystem@192.168.99.1:56500]
16/05/16 02:29:04 INFO Utils: Successfully started service 'sparkDriverActorSystem' on port 56500.
16/05/16 02:29:04 INFO SparkEnv: Registering MapOutputTracker
16/05/16 02:29:04 INFO SparkEnv: Registering BlockManagerMaster
16/05/16 02:29:04 INFO DiskBlockManager: Created local directory at /private/var/folders/d0/x78l2n5s1dx46mkmm6_d24mr0000gn/T/blockmgr-db78c2b3-2dfd-4490-b395-e937ec36ec28
16/05/16 02:29:04 INFO MemoryStore: MemoryStore started with capacity 470.6 MB
16/05/16 02:29:04 INFO SparkEnv: Registering OutputCommitCoordinator
16/05/16 02:29:05 INFO Utils: Successfully started service 'SparkUI' on port 4040.
16/05/16 02:29:05 INFO SparkUI: Started SparkUI at http://192.168.99.1:4040
16/05/16 02:29:05 INFO HttpFileServer: HTTP File server directory is /private/var/folders/d0/x78l2n5s1dx46mkmm6_d24mr0000gn/T/spark-6949016f-ea9c-42ec-8bcd-bb99b04f0f26/httpd-ab2db834-96be-4428-ad27-ae36d0240a7f
16/05/16 02:29:05 INFO HttpServer: Starting HTTP Server
16/05/16 02:29:05 INFO Utils: Successfully started service 'HTTP file server' on port 56501.
16/05/16 02:29:05 INFO SparkContext: Added JAR file:/Users/mtomas/development/private/spark-project-template/target/scala-2.10/spark-project-template_2.10-0.1.jar at http://192.168.99.1:56501/jars/spark-project-template_2.10-0.1.jar with timestamp 1463358545317
16/05/16 02:29:05 INFO Executor: Starting executor ID driver on host localhost
16/05/16 02:29:05 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 56502.
16/05/16 02:29:05 INFO NettyBlockTransferService: Server created on 56502
16/05/16 02:29:05 INFO BlockManagerMaster: Trying to register BlockManager
16/05/16 02:29:05 INFO BlockManagerMasterEndpoint: Registering block manager localhost:56502 with 470.6 MB RAM, BlockManagerId(driver, localhost, 56502)
16/05/16 02:29:05 INFO BlockManagerMaster: Registered BlockManager
16/05/16 02:29:06 INFO MemoryStore: Block broadcast_0 stored as values in memory (estimated size 107.7 KB, free 107.7 KB)
16/05/16 02:29:06 INFO MemoryStore: Block broadcast_0_piece0 stored as bytes in memory (estimated size 9.8 KB, free 117.5 KB)
16/05/16 02:29:06 INFO BlockManagerInfo: Added broadcast_0_piece0 in memory on localhost:56502 (size: 9.8 KB, free: 470.6 MB)
16/05/16 02:29:06 INFO SparkContext: Created broadcast 0 from textFile at SparkApp.scala:14
16/05/16 02:29:06 INFO FileInputFormat: Total input paths to process : 1
16/05/16 02:29:06 INFO SparkContext: Starting job: count at SparkApp.scala:15
16/05/16 02:29:06 INFO DAGScheduler: Got job 0 (count at SparkApp.scala:15) with 3 output partitions
16/05/16 02:29:06 INFO DAGScheduler: Final stage: ResultStage 0 (count at SparkApp.scala:15)
16/05/16 02:29:06 INFO DAGScheduler: Parents of final stage: List()
16/05/16 02:29:06 INFO DAGScheduler: Missing parents: List()
16/05/16 02:29:06 INFO DAGScheduler: Submitting ResultStage 0 (MapPartitionsRDD[2] at filter at SparkApp.scala:15), which has no missing parents
16/05/16 02:29:06 INFO MemoryStore: Block broadcast_1 stored as values in memory (estimated size 3.1 KB, free 120.6 KB)
16/05/16 02:29:06 INFO MemoryStore: Block broadcast_1_piece0 stored as bytes in memory (estimated size 1878.0 B, free 122.4 KB)
16/05/16 02:29:06 INFO BlockManagerInfo: Added broadcast_1_piece0 in memory on localhost:56502 (size: 1878.0 B, free: 470.6 MB)
16/05/16 02:29:06 INFO SparkContext: Created broadcast 1 from broadcast at DAGScheduler.scala:1006
16/05/16 02:29:06 INFO DAGScheduler: Submitting 3 missing tasks from ResultStage 0 (MapPartitionsRDD[2] at filter at SparkApp.scala:15)
16/05/16 02:29:06 INFO TaskSchedulerImpl: Adding task set 0.0 with 3 tasks
16/05/16 02:29:06 INFO TaskSetManager: Starting task 0.0 in stage 0.0 (TID 0, localhost, partition 0,PROCESS_LOCAL, 2255 bytes)
16/05/16 02:29:06 INFO TaskSetManager: Starting task 1.0 in stage 0.0 (TID 1, localhost, partition 1,PROCESS_LOCAL, 2255 bytes)
16/05/16 02:29:06 INFO TaskSetManager: Starting task 2.0 in stage 0.0 (TID 2, localhost, partition 2,PROCESS_LOCAL, 2255 bytes)
16/05/16 02:29:06 INFO Executor: Running task 1.0 in stage 0.0 (TID 1)
16/05/16 02:29:06 INFO Executor: Running task 2.0 in stage 0.0 (TID 2)
16/05/16 02:29:06 INFO Executor: Running task 0.0 in stage 0.0 (TID 0)
16/05/16 02:29:06 INFO Executor: Fetching http://192.168.99.1:56501/jars/spark-project-template_2.10-0.1.jar with timestamp 1463358545317
16/05/16 02:29:07 INFO Utils: Fetching http://192.168.99.1:56501/jars/spark-project-template_2.10-0.1.jar to /private/var/folders/d0/x78l2n5s1dx46mkmm6_d24mr0000gn/T/spark-6949016f-ea9c-42ec-8bcd-bb99b04f0f26/userFiles-5b28db38-75c3-444a-869e-de30918ac4e1/fetchFileTemp1466445307075491976.tmp
16/05/16 02:29:07 INFO Executor: Adding file:/private/var/folders/d0/x78l2n5s1dx46mkmm6_d24mr0000gn/T/spark-6949016f-ea9c-42ec-8bcd-bb99b04f0f26/userFiles-5b28db38-75c3-444a-869e-de30918ac4e1/spark-project-template_2.10-0.1.jar to class loader
16/05/16 02:29:07 ERROR Executor: Exception in task 2.0 in stage 0.0 (TID 2)
java.io.IOException: java.lang.ClassNotFoundException: scala.Some
    at org.apache.spark.util.Utils$.tryOrIOException(Utils.scala:1207)
    at org.apache.spark.Accumulable.readObject(Accumulators.scala:151)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1058)
    at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1900)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
    at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2000)
    at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1891)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
    at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2000)
    at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1924)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
    at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
    at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:76)
    at org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:115)
    at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:194)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: scala.Some
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:348)
    at org.apache.spark.serializer.JavaDeserializationStream$$anon$1.resolveClass(JavaSerializer.scala:68)
    at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1613)
    at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1518)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1774)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
    at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2000)
    at java.io.ObjectInputStream.defaultReadObject(ObjectInputStream.java:501)
    at org.apache.spark.Accumulable$$anonfun$readObject$1.apply$mcV$sp(Accumulators.scala:152)
    at org.apache.spark.util.Utils$.tryOrIOException(Utils.scala:1204)
    ... 24 more
16/05/16 02:29:07 ERROR Executor: Exception in task 1.0 in stage 0.0 (TID 1)
java.io.IOException: java.lang.ClassNotFoundException: scala.Some
    at org.apache.spark.util.Utils$.tryOrIOException(Utils.scala:1207)
    at org.apache.spark.Accumulable.readObject(Accumulators.scala:151)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1058)
    at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1900)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
    at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2000)
    at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1891)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
    at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2000)
    at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1924)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
    at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
    at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:76)
    at org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:115)
    at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:194)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: scala.Some
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:348)
    at org.apache.spark.serializer.JavaDeserializationStream$$anon$1.resolveClass(JavaSerializer.scala:68)
    at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1613)
    at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1518)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1774)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
    at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2000)
    at java.io.ObjectInputStream.defaultReadObject(ObjectInputStream.java:501)
    at org.apache.spark.Accumulable$$anonfun$readObject$1.apply$mcV$sp(Accumulators.scala:152)
    at org.apache.spark.util.Utils$.tryOrIOException(Utils.scala:1204)
    ... 24 more
16/05/16 02:29:07 ERROR Executor: Exception in task 0.0 in stage 0.0 (TID 0)
java.io.IOException: java.lang.ClassNotFoundException: scala.Some
    at org.apache.spark.util.Utils$.tryOrIOException(Utils.scala:1207)
    at org.apache.spark.Accumulable.readObject(Accumulators.scala:151)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1058)
    at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1900)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
    at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2000)
    at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1891)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
    at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2000)
    at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1924)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
    at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
    at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:76)
    at org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:115)
    at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:194)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: scala.Some
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:348)
    at org.apache.spark.serializer.JavaDeserializationStream$$anon$1.resolveClass(JavaSerializer.scala:68)
    at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1613)
    at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1518)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1774)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
    at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2000)
    at java.io.ObjectInputStream.defaultReadObject(ObjectInputStream.java:501)
    at org.apache.spark.Accumulable$$anonfun$readObject$1.apply$mcV$sp(Accumulators.scala:152)
    at org.apache.spark.util.Utils$.tryOrIOException(Utils.scala:1204)
    ... 24 more
16/05/16 02:29:07 ERROR TaskResultGetter: Could not deserialize TaskEndReason: ClassNotFound with classloader org.apache.spark.util.MutableURLClassLoader@7da96d86
16/05/16 02:29:07 ERROR TaskResultGetter: Could not deserialize TaskEndReason: ClassNotFound with classloader org.apache.spark.util.MutableURLClassLoader@7da96d86
16/05/16 02:29:07 ERROR TaskResultGetter: Could not deserialize TaskEndReason: ClassNotFound with classloader org.apache.spark.util.MutableURLClassLoader@7da96d86
16/05/16 02:29:07 WARN TaskSetManager: Lost task 2.0 in stage 0.0 (TID 2, localhost): UnknownReason
16/05/16 02:29:07 ERROR TaskSetManager: Task 2 in stage 0.0 failed 1 times; aborting job
16/05/16 02:29:07 INFO TaskSchedulerImpl: Removed TaskSet 0.0, whose tasks have all completed, from pool
16/05/16 02:29:07 WARN TaskSetManager: Lost task 0.0 in stage 0.0 (TID 0, localhost): UnknownReason
16/05/16 02:29:07 INFO TaskSchedulerImpl: Removed TaskSet 0.0, whose tasks have all completed, from pool
16/05/16 02:29:07 WARN TaskSetManager: Lost task 1.0 in stage 0.0 (TID 1, localhost): UnknownReason
16/05/16 02:29:07 INFO TaskSchedulerImpl: Removed TaskSet 0.0, whose tasks have all completed, from pool
16/05/16 02:29:07 INFO TaskSchedulerImpl: Cancelling stage 0
16/05/16 02:29:07 INFO DAGScheduler: ResultStage 0 (count at SparkApp.scala:15) failed in 0.170 s
16/05/16 02:29:07 INFO DAGScheduler: Job 0 failed: count at SparkApp.scala:15, took 0.269086 s
[error] (run-main-0) org.apache.spark.SparkException: Job aborted due to stage failure: Task 2 in stage 0.0 failed 1 times, most recent failure: Lost task 2.0 in stage 0.0 (TID 2, localhost): UnknownReason
[error] Driver stacktrace:
16/05/16 02:29:07 ERROR ContextCleaner: Error in cleaning thread
java.lang.InterruptedException
    at java.lang.Object.wait(Native Method)
    at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
    at org.apache.spark.ContextCleaner$$anonfun$org$apache$spark$ContextCleaner$$keepCleaning$1.apply$mcV$sp(ContextCleaner.scala:176)
    at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1180)
    at org.apache.spark.ContextCleaner.org$apache$spark$ContextCleaner$$keepCleaning(ContextCleaner.scala:173)
    at org.apache.spark.ContextCleaner$$anon$3.run(ContextCleaner.scala:68)
16/05/16 02:29:07 ERROR Utils: uncaught error in thread SparkListenerBus, stopping SparkContext
java.lang.InterruptedException
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:998)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
    at java.util.concurrent.Semaphore.acquire(Semaphore.java:312)
    at org.apache.spark.util.AsynchronousListenerBus$$anon$1$$anonfun$run$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(AsynchronousListenerBus.scala:66)
    at org.apache.spark.util.AsynchronousListenerBus$$anon$1$$anonfun$run$1$$anonfun$apply$mcV$sp$1.apply(AsynchronousListenerBus.scala:65)
    at org.apache.spark.util.AsynchronousListenerBus$$anon$1$$anonfun$run$1$$anonfun$apply$mcV$sp$1.apply(AsynchronousListenerBus.scala:65)
    at scala.util.DynamicVariable.withValue(DynamicVariable.scala:57)
    at org.apache.spark.util.AsynchronousListenerBus$$anon$1$$anonfun$run$1.apply$mcV$sp(AsynchronousListenerBus.scala:64)
    at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1180)
    at org.apache.spark.util.AsynchronousListenerBus$$anon$1.run(AsynchronousListenerBus.scala:63)
org.apache.spark.SparkException: Job aborted due to stage failure: Task 2 in stage 0.0 failed 1 times, most recent failure: Lost task 2.0 in stage 0.0 (TID 2, localhost): UnknownReason
Driver stacktrace:
    at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1431)
    at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1419)
    at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1418)
    at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
    at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
    at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1418)
    at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:799)
    at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:799)
    at scala.Option.foreach(Option.scala:236)
    at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:799)
    at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1640)
    at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1599)
    at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1588)
    at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
    at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:620)
    at org.apache.spark.SparkContext.runJob(SparkContext.scala:1832)
    at org.apache.spark.SparkContext.runJob(SparkContext.scala:1845)
    at org.apache.spark.SparkContext.runJob(SparkContext.scala:1858)
    at org.apache.spark.SparkContext.runJob(SparkContext.scala:1929)
    at org.apache.spark.rdd.RDD.count(RDD.scala:1157)
    at com.company.sample.App$.main(SparkApp.scala:15)
    at com.company.sample.App.main(SparkApp.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:731)
    at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
    at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
    at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
    at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at sbt.Run.invokeMain(Run.scala:67)
    at sbt.Run.run0(Run.scala:61)
    at sbt.Run.sbt$Run$$execute$1(Run.scala:51)
    at sbt.Run$$anonfun$run$1.apply$mcV$sp(Run.scala:55)
    at sbt.Run$$anonfun$run$1.apply(Run.scala:55)
    at sbt.Run$$anonfun$run$1.apply(Run.scala:55)
    at sbt.Logger$$anon$4.apply(Logger.scala:84)
    at sbt.TrapExit$App.run(TrapExit.scala:248)
    at java.lang.Thread.run(Thread.java:745)
java.lang.RuntimeException: Nonzero exit code: 1
    at scala.sys.package$.error(package.scala:27)
    at sbtsparksubmit.SparkSubmitPlugin$autoImport$SparkSubmitSetting$$anonfun$defaultSettings$1$$anonfun$apply$1$$anonfun$apply$2$$anonfun$apply$4.apply(SparkSubmitPlugin.scala:88)
    at sbtsparksubmit.SparkSubmitPlugin$autoImport$SparkSubmitSetting$$anonfun$defaultSettings$1$$anonfun$apply$1$$anonfun$apply$2$$anonfun$apply$4.apply(SparkSubmitPlugin.scala:88)
    at scala.Option.foreach(Option.scala:236)
    at sbtsparksubmit.SparkSubmitPlugin$autoImport$SparkSubmitSetting$$anonfun$defaultSettings$1$$anonfun$apply$1$$anonfun$apply$2.apply(SparkSubmitPlugin.scala:88)
    at sbtsparksubmit.SparkSubmitPlugin$autoImport$SparkSubmitSetting$$anonfun$defaultSettings$1$$anonfun$apply$1$$anonfun$apply$2.apply(SparkSubmitPlugin.scala:51)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
    at sbt.std.Transform$$anon$4.work(System.scala:63)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.Execute.work(Execute.scala:237)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
[error] (*:sampleApp) Nonzero exit code: 1
[error] Total time: 14 s, completed May 16, 2016 2:29:07 AM
16/05/16 02:29:07 INFO SparkUI: Stopped Spark web UI at http://192.168.99.1:4040
16/05/16 02:29:07 INFO DiskBlockManager: Shutdown hook called
16/05/16 02:29:07 INFO ShutdownHookManager: Shutdown hook called
16/05/16 02:29:07 INFO ShutdownHookManager: Deleting directory /private/var/folders/d0/x78l2n5s1dx46mkmm6_d24mr0000gn/T/spark-6949016f-ea9c-42ec-8bcd-bb99b04f0f26
16/05/16 02:29:07 INFO ShutdownHookManager: Deleting directory /private/var/folders/d0/x78l2n5s1dx46mkmm6_d24mr0000gn/T/spark-6949016f-ea9c-42ec-8bcd-bb99b04f0f26/httpd-ab2db834-96be-4428-ad27-ae36d0240a7f
16/05/16 02:29:07 INFO ShutdownHookManager: Deleting directory /private/var/folders/d0/x78l2n5s1dx46mkmm6_d24mr0000gn/T/spark-6949016f-ea9c-42ec-8bcd-bb99b04f0f26/userFiles-5b28db38-75c3-444a-869e-de30918ac4e1
```

Any clues / plans about resolving this ?

Thanks a lot !

**Comment by saurfang** [comment]
It looks like there are things missing or in conflict on the classpath. I was able to use this with Spark 1.6 without a problem. If you can share a minimal reproducible example on Github, I can take a look.

**Comment by mdrajibulislam** [comment]
I got the same error when I am using scalaVersion := "2.11.5" but later I have changed sbt file as below 
javacOptions ++= Seq("-source", "1.8", "-target", "1.8")
scalaVersion := "2.11.7"
and also try to minimize your dependency. 
There is another solution you may use, line to sbt file : add fork := true

**Comment by worldwar2008** [comment]
I ave meet the same problem in local mode;
scala verson:2.10.4
spark:1.5.2

**Comment by shengshen** [comment]
Add this line at the end of your project file. You can fix the bug.
eg: 
//val sc = new SparkContext(conf)
sc.stop()

**Comment by todesking** [comment]
I had same issue(In my case, `scala.concurrent.duration.FiniteDuration` not found).

SBT's classloader is very complex and sometimes cause this kind of problem.

As mentioned above,

```scala
// build.sbt
fork := true
```

is the solution.

(Maybe this is good for default configuration, or put in readme)

**Comment by saurfang** [comment]
Seems like a good addition to the readme. Anyone is interested in putting together a PR?
