### ISSUE TITLE
Problems running with spark 2

### ISSUE THREAD

**Issue by xrl** [saurfang/sbt-spark-submit#5]
I'm new to Spark/Scala/SBT but I got this far. I have been able to use this spark-submit command no problem:

```
LP-XLANGE-OSX:lalala-streaming xlange$ spark-submit --packages org.apache.spark:spark-streaming_2.11:2.0.1  --class SimpleKafkaReader target/scala-2.11/lalala-streaming_2.11-1.0.jar
```

Note: I installed spark-submit from mac homebrew (hence why it's in my `$PATH`).

And now I'm trying to use the `sbt-spark-submit` plugin:

```
$ sbt "sparkSubmit --packages org.apache.spark:spark-streaming_2.11:2.0.1 --class SimpleKafkaReader --master local[4]"
[info] Loading global plugins from /Users/xlange/.sbt/0.13/plugins
[info] Loading project definition from /Users/xlange/IdeaProjects/lalala-streaming/project
[info] Set current project to lalala-streaming (in build file:/Users/xlange/IdeaProjects/lalala-streaming/)
[warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list
[info] Running org.apache.spark.deploy.SparkSubmit --master local /Users/xlange/IdeaProjects/lalala-streaming/target/scala-2.11/lalala-streaming_2.11-1.0.jar --packages org.apache.spark:spark-streaming_2.11:2.0.1 --class SimpleKafkaReader --master local[4]
Error: No main class set in JAR; please specify one with --class
Run with --help for usage help or --verbose for debug output

Exception: sbt.TrapExitSecurityException thrown from the UncaughtExceptionHandler in thread "run-main-0"
java.lang.RuntimeException: Nonzero exit code: 1
        at scala.sys.package$.error(package.scala:27)
        at sbtsparksubmit.SparkSubmitPlugin$autoImport$SparkSubmitSetting$$anonfun$defaultSettings$1$$anonfun$apply$1$$anonfun$apply$2$$anonfun$apply$4.apply(SparkSubmitPlugin.scala:88)
        at sbtsparksubmit.SparkSubmitPlugin$autoImport$SparkSubmitSetting$$anonfun$defaultSettings$1$$anonfun$apply$1$$anonfun$apply$2$$anonfun$apply$4.apply(SparkSubmitPlugin.scala:88)
        at scala.Option.foreach(Option.scala:236)
        at sbtsparksubmit.SparkSubmitPlugin$autoImport$SparkSubmitSetting$$anonfun$defaultSettings$1$$anonfun$apply$1$$anonfun$apply$2.apply(SparkSubmitPlugin.scala:88)
        at sbtsparksubmit.SparkSubmitPlugin$autoImport$SparkSubmitSetting$$anonfun$defaultSettings$1$$anonfun$apply$1$$anonfun$apply$2.apply(SparkSubmitPlugin.scala:51)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:235)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[error] (*:sparkSubmit) Nonzero exit code: 1
[error] Total time: 1 s, completed Oct 30, 2016 2:27:20 PM
```

**Comment by xrl** [comment]
Looks like it's a problem with the jar's path being specified too early in the command?\

**Comment by saurfang** [comment]
try `sbt "sparkSubmit --packages org.apache.spark:spark-streaming_2.11:2.0.1 --class SimpleKafkaReader --master local[4] --"` because I have to distinguish what arguments are for spark and what are for application somehow by default if you don't have `--` all arguments are treated as application arguments.

Feel free to reopen if this doesn't solve the issue.
